[package]
name = "KFS"
version = "1.0.0"
authors = ["Ychun, Schaehun"]
edition = "2021"

[dependencies]
spin = "0.9.8"
volatile = "0.2.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
